### PR TITLE
Ccx0022tracking

### PR DESCRIPTION
**Pull request by vgoodric**
There is no issue attached to this.  It was a follow up request in Slack.

To view this feature, simulate a mobile screen size while at the top of the page.  A small button with a bouncing arrow should appear.  The new tracking should contain "scrollbuttonPressed"

Test URLs:
- Before: https://main--express-website--adobe.hlx3.page/express/create/flyer
- After: https://ccx0022tracking--express-website--adobe.hlx3.page/express/create/flyer?lighthouse=on

### CODE REVIEW

**Review by williambsm — APPROVED** [review]
This looks good to me.

**Review by williambsm — CHANGES_REQUESTED** [review]
I think it's a good idea to also update the adobeSparkName because it is currently defaulted to 'templatePressed' which is not accurate.

**Comment by vgoodric** [comment]
@williambsm I'm not a fan of having an if with the same condition as above, but this feels like the best place to make that exception without updating more than necessary.  The other possibility is to move the setting of the sparkEventName above the if/else and then update it in the one clause where it's different.

**Comment by williambsm** [comment]
In other parts of the analytics system, both of them are defined at the same time. But this will do for now. Thanks!

**Review by williambsm — APPROVED** [review]

**Pull request merged**
