### PR TITLE
fix(template-list): ignore formatting in 2nd column

### PR DESCRIPTION
**Pull request by rofe**
Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/rofe/template-list
- After: https://template-list-resilience--express-website--adobe.hlx.page/drafts/rofe/template-list?lighthouse=on

### CODE REVIEW

**Review by davidnuescheler — APPROVED** [review]
looks good to me but could be regression prone. so it could be worth while to test on the top 20 pages or so...

**Comment by rofe** [comment]
@davidnuescheler I tested the [homepage](https://template-list-resilience--express-website--adobe.hlx.page/express/), all "create" pages linked from the nav as well as the [blog post](https://template-list-resilience--express-website--adobe.hlx.page/express/learn/blog/earth-day-quote-posters) where the issue originally occurred. So far I couldn't spot any regressions

@m-cao @timliu-adobe do you have more crucial pages with template lists on them I should look at before merging?

**Comment by m-cao** [comment]
Thanks for checking @rofe . Yeah I'd say any page listed in the Create tab of the nav would be a good place to do some regression tests on:
image

That said, what was the issue here again that was fixed? Not sure I have the full context here, but was it that this first template in the template list had a very large bolded "Edit this template" CTA?
image

**Comment by rofe** [comment]
@m-cao yes, that's the issue someone ran into on a blog post: there was extra formatting added to the "edit template" link (not always visible in word online, unfortunately, the font looked like it was normal text), so I added resilience around that.

**Comment by timliu-adobe** [comment]
Thanks for the tag @rofe and for the support on this fix! No additional crucial pages that I can think of beyond the ones Michael called out under "Create."

**Comment by rofe** [comment]
Thanks @m-cao and @timliu-adobe. I think we're all set!
cc @davidnuescheler

**Review by kptdobe — APPROVED** [review]

**Pull request merged**
