### PR TITLE
Release Template-V2

### PR DESCRIPTION
**Pull request by JingleH**
Fix https://jira.corp.adobe.com/browse/MWPW-133170

Release wiki: https://wiki.corp.adobe.com/display/adobedotcom/Templates+v2+Release

All code changes should be backward-compatible. Namely, after code merged, old content should still display fine

Samples of potentially impacted pages to be verified:
- https://www.adobe.com/express/templates/
- https://www.adobe.com/express/templates/flyer/christmas
- https://www.adobe.com/express/templates/search?tasks=banner&phformat=2:3&topics=hello&q=hello
- https://www.adobe.com/express/templates/create/flyer
- [https://www.adobe.com/fr/express/](https://www.adobe.com/express/templates/)
- https://www.adobe.com/express/learn/students

Test URLs:
- Before: https://main--express-website--adobe.hlx.live/express/templates/flyer/christmas?lighthouse=on
- After: https://stage--express-website--adobe.hlx.page/express/templates/flyer/christmas?lighthouse=on

### CODE REVIEW

**Review by vhargrave — CHANGES_REQUESTED** [review]
We shouldn't have default options that return nothing in the list. 
Additionally, the page title is not set here

https://github.com/adobe/express-website/assets/115231412/58634720-1b0c-4a57-ad6b-06c4801bc9a8

**Comment by vhargrave** [comment]
> 

Switching back and forth between the filter for oldest to newest and newest to oldest is showing some of the same results at the top. That seems completely wrong to me

https://github.com/adobe/express-website/assets/115231412/e75aa68e-c8ca-4cbf-837a-c633465f6005

**Comment by vhargrave** [comment]
On mobile there probably shouldn't be a large space between the search field and content below
image

**Comment by vhargrave** [comment]
> > We shouldn't have default options that return nothing in the list. Additionally, the page title is not set here
> > Screen.Recording.2023-06-26.at.10.00.24.mov
> 
> This search suggestion list is likely not done being authored yet. And, If a templates/ link returns an empty page with no title like that, it's because the metadata sheet doesn't have a row for it. In prod environment, this type of pages will be properly handled and actually redirect to express/templates root page.

ok, if you're sure then we're good 👍

**Review by qiyundai — APPROVED** [review]

**Review by apganapa — APPROVED** [review]

**Review by vhargrave — APPROVED** [review]

**Pull request merged**
