### PR TITLE
[MWPW-1228224] Pricing Content Toggle block variants

### PR DESCRIPTION
**Pull request by williambsm**
Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=34618) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix https://jira.corp.adobe.com/browse/MWPW-122824

Test URLs (for previous works involving the content toggle block):
- Before: https://main--express-website--adobe.hlx.page/education/express/
- After: https://m-122824-1--express-website--webistry-development.hlx.page/education/express/?lighthouse=on

Test URLs (for new variants):
- Before: https://main--express-website--adobe.hlx.page/drafts/casey/content-toggle/pricing
- After: https://m-122824-1--express-website--webistry-development.hlx.page/drafts/casey/content-toggle/pricing?lighthouse=on

### CODE REVIEW

**Comment by williambsm** [comment]
Feedback for the Pull Request (the work is done by @toka1300 but reviewed by me):

1. The external linking functionality needs to be functional at a global level, not variant restricted.
2. The tooltip display functionality should also be functional at a global level, not variant restricted.
3. There is a weird right spacing issue between the last button and the end of the box.
4. Rather than wrapping a link tag around the button if the link is external, replace the button with a link.
5. When an external button is clicked, the tab searching functionality should be prevented.
6. I feel off about the toggleMargin function, let's review this after my feedback is implemented.

**Comment by qiyundai** [comment]
@williambsm @toka1300 do we still need this?

**Comment by toka1300** [comment]
I don't think so, if my memory serves, we switched to a different branch for merging into main?

**Comment by apganapa** [comment]
Closing this PR as discussed in the technical since it is not needed and required changes are already merged through different PR.

**Pull request closed without merging**
