### PR TITLE
fix: experimention selecting empty variant

### PR DESCRIPTION
**Pull request by ravkiran**
Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=34618) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes [MWPW-132354](https://jira.corp.adobe.com/browse/MWPW-132354)

When the page is accessed from a browser with reduced width < 600, we'll set the experiment config with out the `selectedVariant` but we won't run the experiment. So, updating the code to set the experimentation config only if the audience matches (i.e, `config.run` is true)

Test URLs:
Before: https://main--express-website--adobe.hlx.page/express/spotlight/test/remove-background-new?experiment=ccx0027a%2Fchallenger-1 
After: https://ccx0027-empty-variant--express-website--adobe.hlx.page/express/spotlight/test/remove-background-new?experiment=ccx0027a%2Fchallenger-1

### CODE REVIEW

**Comment by vhargrave** [comment]
Change looks fine, but can you structure the PR as described so that all checks succeed?
- always link Jira issue
- provide before and after urls showcasing the fix or change 

additionally we're kind of in a code freeze until Thursday - so no merging to stage or main unless it's urgent

**Comment by apganapa** [comment]
@ravkiran everything needs to go via stage branch, so please close this and raise it against stage branch first.

**Comment by ravkiran** [comment]
> @ravkiran everything needs to go via stage branch, so please close this and raise it against stage branch first.

@apganapa are you merging stage to main regularly? Is there a wiki page about this policy and timeline about when stage will be merged to main? Last time I've checked a couple of months ago, `stage` is obsolete, so we've been merging to `main` since ~ last 5 months.

**Review by vhargrave — APPROVED** [review]
looks fine - code freeze is now over so you can merge.

**Review by apganapa — APPROVED** [review]

**Pull request merged**
