### PR TITLE
fix: added missing trailing slash for edu redirects

### PR DESCRIPTION
**Pull request by meryllblanchet**
Fix AEXG-3024

Test URLs:
- Before: 

https://main--express-website--adobe.hlx.live/express/edu?locale=jcy-GB
https://main--express-website--adobe.hlx.live/express/edu?locale=da-DK
https://main--express-website--adobe.hlx.live/express/edu?locale=de-DE
https://main--express-website--adobe.hlx.live/express/edu?locale=en-US
https://main--express-website--adobe.hlx.live/express/edu?locale=es-ES
https://main--express-website--adobe.hlx.live/express/edu?locale=fi-FI
https://main--express-website--adobe.hlx.live/express/edu?locale=fr-FR
https://main--express-website--adobe.hlx.live/express/edu?locale=it-IT
https://main--express-website--adobe.hlx.live/express/edu?locale=ja-JP
https://main--express-website--adobe.hlx.live/express/edu?locale=ko-KR
https://main--express-website--adobe.hlx.live/express/edu?locale=nb-NO
https://main--express-website--adobe.hlx.live/express/edu?locale=nl-NL
https://main--express-website--adobe.hlx.live/express/edu?locale=pt-BR 
https://main--express-website--adobe.hlx.live/express/edu?locale=sv-SE
https://main--express-website--adobe.hlx.live/express/edu?locale=zh-Hans-CN
https://main--express-website--adobe.hlx.live/express/edu?locale=zh-Hant-TW

https://main--express-website--adobe.hlx.live/testing/edu?locale=jcy-GB
https://main--express-website--adobe.hlx.live/testing/edu?locale=es-ES
https://main--express-website--adobe.hlx.live/express/edu?locale=da-DK
https://main--express-website--adobe.hlx.live/testing/edu?locale=pt-BR
https://main--express-website--adobe.hlx.live/testing/edu?locale=pt-BR

https://main--express-website--adobe.hlx.live/ca_fr/express/
https://main--express-website--adobe.hlx.live/africa/express/
https://main--express-website--adobe.hlx.live/es-ES/express/
https://main--express-website--adobe.hlx.live/hk_zh/express/
https://main--express-website--adobe.hlx.live/ja-JP/express/

- After: 

https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=jcy-GB
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=da-DK
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=de-DE
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=en-US
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=es-ES
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=fi-FI
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=fr-FR
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=it-IT
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=ja-JP
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=ko-KR
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=nb-NO
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=nl-NL
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=pt-BR 
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=sv-SE
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=zh-Hans-CN
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=zh-Hant-TW

https://fix-client-redirect--express-website--adobe.hlx.live/testing/edu?locale=jcy-GB
https://fix-client-redirect--express-website--adobe.hlx.live/testing/edu?locale=es-ES
https://fix-client-redirect--express-website--adobe.hlx.live/express/edu?locale=da-DK
https://fix-client-redirect--express-website--adobe.hlx.live/testing/edu?locale=pt-BR
https://fix-client-redirect--express-website--adobe.hlx.live/testing/edu?locale=pt-BR

https://fix-client-redirect--express-website--adobe.hlx.live/ca_fr/express/
https://fix-client-redirect--express-website--adobe.hlx.live/africa/express/
https://fix-client-redirect--express-website--adobe.hlx.live/es-ES/express/
https://fix-client-redirect--express-website--adobe.hlx.live/hk_zh/express/
https://fix-client-redirect--express-website--adobe.hlx.live/ja-JP/express/

### CODE REVIEW

**Review by ramboz — COMMENTED** [review]
Looks good to me, but we still have a use case to cover as per slack discussion

**Review by rofe — APPROVED** [review]

**Comment by meryllblanchet** [comment]
@sirgil2009 after more tests, we still observe some inconsistencies:

https://fix-client-redirect--express-website--adobe.hlx.page/edu/?locale=it-IT
should redirect to
https://www.adobe.com/it/education/express/
but redirects to 
https://www.adobe.com/tw/education/express/?locale=it-IT

Also, http://localhost:3000/404.html turns into an endless loop, because the code sets `userLocale` to `404.html` at line 64.

**Review by ramboz — APPROVED** [review]
Looks good overall.

There are a few opportunities to improve the maintainability and optimize the code:
- maybe combining the 2 first `if`/`else if` clauses since they share a lot of code
- aligning variable names so they are more verbose and descriptive
- suffix takes 2 `f`

**Comment by sirgil2009** [comment]
> Looks good overall.
> 
> There are a few opportunities to improve the maintainability and optimize the code:
> 
>     * maybe combining the 2 first `if`/`else if` clauses since they share a lot of code
> 
>     * aligning variable names so they are more verbose and descriptive
> 
>     * suffix takes 2 `f`

@ramboz  Ok, Awesome!  I'll refactor and make these improvements including extracting the js code into 
a separate file, so I can write unit test for it.  I am creating a new ticket for that.

**Comment by meryllblanchet** [comment]
Hello @sirgil2009 @ramboz 

I think we're getting close! I did some further tests that still don't pass:

> https://fix-client-redirect--express-website--adobe.hlx.live/testing/edu?locale=jcy-GB
> https://fix-client-redirect--express-website--adobe.hlx.live/testing/edu?locale=es-ES
> https://fix-client-redirect--express-website--adobe.hlx.live/testing/edu?locale=da-DK
> https://fix-client-redirect--express-website--adobe.hlx.live/testing/edu?locale=pt-BR
> https://fix-client-redirect--express-website--adobe.hlx.live/testing/edu?locale=pt-BR

This is not working - there's a typo in `euducation`.

> https://fix-client-redirect--express-website--adobe.hlx.live/edu?locale=pt-BR

This special cases where express is not in the URL are not working. Here it redirects to https://www.adobe.com/education/express/?locale=jcy-GB and should redirect to https://www.adobe.com/br/education/.

**Comment by meryllblanchet** [comment]
LGTM now @sirgil2009 !

**Pull request merged**
