### PR TITLE
feat(mobile-icons): added mobile icons

### PR DESCRIPTION
**Pull request by So1ene**
Test URL: https://mobile-icons--express-website--webistry-development.hlx3.page/drafts/solene/mobile-apps

Fixes: https://github.com/adobe/express-website-issues/issues/323

### Icons added: ###
- apple-store.svg
- google-store.svg
- microsoft-store.svg
- galaxy-store.svg

### Authoring: ### 
Simply create a link with the badge-name between `{{icon-` and `}}`
image

### CODE REVIEW

**Review by rofe — APPROVED** [review]

**Comment by rofe** [comment]
@So1ene looking good! 2 things:
1. let's rename `google-play` to `google-store` to align with the other `*-store` icons
2. change the syntax from `:foo:` to `{{icon-foo}}` in authoring: the earlier is deprecated and may be removed from the pipeline.

**Comment by So1ene** [comment]
> @So1ene looking good! 2 things:
> 
> 1. let's rename `google-play` to `google-store` to align with the other `*-store` icons
> 2. change the syntax from `:foo:` to `{{icon-foo}}` in authoring: the earlier is deprecated and may be removed from the pipeline.

Thanks for your feedback, I agree that `{{icon-foo}}` is a much better syntax for authoring, I will fix it right away.

As for the google play icon, 'google store' is a different thing than google play `https://store.google.com/` so maybe we should call it `google-play-store`? It seems a bit long but it would avoid confusion for the authors

**Comment by rofe** [comment]
> 'google store' is a different thing than 'google play' `https://store.google.com/`

Agreed. But then, techniclaly 'apple store' is different from `apple app store` - shoul we rename the icon to `apple-app-store`? 😉

**Comment by So1ene** [comment]
> > 'google store' is a different thing than 'google play' `https://store.google.com/`
> 
> Agreed. But then, techniclaly 'apple store' is different from `apple app store` - shoul we rename the icon to `apple-app-store`? 😉

Touché 
I guess when I hear "google store" I just dont think of "google play" :')

**Review by rofe — APPROVED** [review]

**Pull request merged**
