### PR TITLE
fix(columns-block): remove max-width rule and fix inconsistent paddings

### PR DESCRIPTION
**Pull request by So1ene**
- Fixes https://github.com/adobe/express-website-issues/issues/298

### CODE REVIEW

**Review by rofe — CHANGES_REQUESTED** [review]
@So1ene Alignment generally looks a lot better on the top SEO pages, but I noticed a regression on the education homepage (`.columns.highlight`):
image
image

**Comment by rofe** [comment]
Bonus: this also fixes the 1st issue mentioned in https://github.com/adobe/express-website-issues/issues/299 🤗

**Comment by So1ene** [comment]
> @So1ene Alignment generally looks a lot better on the top SEO pages, but I noticed a regression on the education homepage (`.columns.highlight`): image image

Good catch!

**Comment by So1ene** [comment]
The new commits aren't being shown in this pull request, I made a new one here: https://github.com/Webistry-Development/express-website/pull/6

**Pull request closed without merging**
