### PR TITLE
Mwpw 117565 update

### PR DESCRIPTION
**Pull request by qiyundai**
Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=34618) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix Mwpw 117565

Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/create/flyer1
- Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/create/flyer2
- After: https://mwpw-117565-update--express-website--webistry-development.hlx.page/drafts/qiyundai/create/flyer1?lighthouse=on
- After: https://mwpw-117565-update--express-website--webistry-development.hlx.page/drafts/qiyundai/create/flyer2?lighthouse=on

### CODE REVIEW

**Comment by rofe** [comment]
@qiyundai @abhinch @skelleyadobe 
1. I think the holiday block collapse is happening too soon and is therefore contributing to a high CLS (cumulative layout shift). Can we try to keep it expanded for a little while longer? 
2. The high TBT (total blocking time) is also a concern. I suspect it is coming from the snow animation. Maybe there's a way to lazy load it?

**Comment by qiyundai** [comment]
> @qiyundai @abhinch @skelleyadobe
> 
> 1. I think the holiday block collapse is happening too soon and is therefore contributing to a high CLS (cumulative layout shift). Can we try to keep it expanded for a little while longer?
> 2. The high TBT (total blocking time) is also a concern. I suspect it is coming from the snow animation. Maybe there's a way to lazy load it?

1. all collapse delay is authored in the word doc. Currently setting flyer2 with 6 seconds, comparing with flyer1 at 3 seconds, as a "control" page.

**Comment by skelleyadobe** [comment]
Agreed, it closes too quickly. What is it set to currently? Can we take a look at 3 and 5 second versions? 

A lazy load of the snow sounds good too. Can we have that slowly fade in 1-2 seconds after load? 

Can we also adjust the background color here and are we able to adjust the graphic in the top left corner as well? 

@qiyundai @abhinch

**Comment by qiyundai** [comment]
> 

flyer1 is 3 seconds, flyer2 is 5 seconds.

@rofe Could you please advise how we should go about lazy-loading a canvas element? @skelleyadobe Added 2s fade-in and control of the background color in the word doc. Please refer to flyer2 for the method to change the background color

**Comment by skelleyadobe** [comment]
@qiyundai I think you can lazy load the snow animation as well if that will help. 

Flyer 2 isn't loading on my end.

**Comment by rofe** [comment]
> Flyer 2 isn't loading on my end.

It is loading for me. I like the 5s delay better visually. Google LHS still dings us on CLS though. Ideal would be 7 - 10s. But since it can be defind in authoring, no code change needed here.

cc @skelleyadobe @qiyundai

**Comment by rofe** [comment]
TBT is still a whopping 1000ms - probably due to the canvas/background animation...

> Could you please advise how we should go about lazy-loading a canvas element? 

I meant something like displaying a placeholder with just the background color and maybe a spinner, and then after a "safe" delay create the canvas element and load the background animation... not the same experience as now for sure, but might still feel faster on mobile.

**Comment by rofe** [comment]
@qiyundai i just realized that `template-list` isn't part of the `LCP_BLOCKS` and therefore the LCP is taking too long. Can you add it there and make sure the block is executed synchronously?

**Pull request closed without merging**
