### PR TITLE
MWPW-129166 fix font issue japanese

### PR DESCRIPTION
**Pull request by vhargrave**
Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=34618) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix [MWPW-129166](https://jira.corp.adobe.com/browse/MWPW-129166)

Test URLs:
- Before: https://main--express-website--adobe.hlx.page/jp/express/?lighthouse=on
- After: https://japanese-font--express-website--adobe.hlx.page/jp/express/?lighthouse=on

### CODE REVIEW

**Review by apganapa — APPROVED** [review]

**Comment by rofe** [comment]
@vhargrave this solution seems to add significant TBT. I'd recommend exploring using this loading mechanism only for certain languages, or further delaying it...

**Comment by vhargrave** [comment]
> @vhargrave this solution seems to add significant TBT. I'd recommend exploring using this loading mechanism only for certain languages, or further delaying it...

@rofe I've restricted the fonts to only load for japanese atm, but can't do too much about the total blocking time as this is being caused by the typekit script. I could technically heavily delay the font loading so that the browser initially loads the "wrong" font, but content wouldn't be blocked. This would trick the LH test and give us a much better score. User experience wise though, japanese users would see an ugly flash of unstyled text after around 4-5 seconds of a page loading, which is probably worse than making them wait for two seconds before they can interact with the page. I took a little look at milo and the adobe confluence and couldn't find anything to really speed up the font loading asides from just downloading them manually and not using typekit. I'm not sure this is the best approach though.

**Comment by rofe** [comment]
In western font loading, we make use of "fallback fonts", i.e. CSS-modified system fonts made to look and run similarly wide as the font to be loaded, so the flashing of unstyled text would not be as jarring. I don't know however if such a technique could be used with a japanese font. Maybe @MasonPinZ would know.

**Comment by vhargrave** [comment]
> In western font loading, we make use of "fallback fonts", i.e. CSS-modified system fonts made to look and run similarly wide as the font to be loaded, so the flashing of unstyled text would not be as jarring. I don't know however if such a technique could be used with a japanese font. Maybe @MasonPinZ would know.

ok - it still feels a bit hacky though since you're "tricking" the browser by heavily delaying the loading of the font you want. At that point I almost wonder why we load the font at all..

**Review by qiyundai — APPROVED** [review]
The code looks good. Besides the TBT impact, I only noticed that the English font changes in size and weight with the typekit loaded. Not sure if Sean was talking about that earlier during the sync today but otherwise I think this is one of the better solutions we have for the moment.

**Pull request merged**
